version: '2'
services:
  webservice:
    build:
      context: ./server
      dockerfile: Dockerfile
    # command: sh -c 'npm install; npm run migrate; npm run seed; npm start'
    command: sh -c 'cd /server; ls'
    volumes:
      - ./server:/server
    depends_on:
      - db
    ports:
      - 3000:3000
    links:
      - db
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DOCKER_ENV=true

  db:
    image: kiasaki/alpine-postgres:latest
    ports:
      - 32776:5432
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=admin
      - POSTGRES_DB=vagalivre
      - PGDATA=/var/lib/postgresql/data
