version: '2'
services:
  webservice:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: sh -c 'npm install; npm run migrate; npm run seed; npm test'
    depends_on:
      - db
    volumes:
      - ./server:/server
    ports:
      - 3000:3000
    links:
      - db
    environment:
      - NODE_ENV=test

  db:
    image: postgres:9.4
    ports:
      - 32775:5432
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=admin
      - POSTGRES_DB=vagalivre
      - PGDATA=/var/lib/test-db/data
