version: '2'
services:
  webservice:
    build: ./server
    command: npm run start-dev
    depends_on:
      - databasedev
    volumes:
      - /Users/armandomagalhaes/Documents/Projetos/Uvv/Vans/server:/server
    ports:
      - 3000:3000
    links:
      - databasedev
    environment:
      - NODE_ENV=development

  databasedev:
    image: postgres:9.4
    ports:
      - 32776:5432
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=admin
      - POSTGRES_DB=vagalivre
      - PGDATA=/var/lib/dev-db/data
