version: '2'
services:
  db:
    image: postgres:9.4
    ports:
      - 32776:5432
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=admin
      - POSTGRES_DB=vagalivre
      - PGDATA=/var/lib/dev-db/data

  webservice:
    build: ./server
    command: sh -c 'npm run migrate; npm run seed; npm run start-dev'
    depends_on:
      - db
    ports:
      - 3000:3000
    links:
      - db:postgres
    environment:
      - NODE_ENV=development
